spring:
  profiles.active: mysql
  liquibase:
    enabled: false    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true
      logging: sysout
      log-format: '%(sql);'
      timestamp-format: 'yyyy-MM-dd HH24:MI:SS'
    enabled: true